### ISSUE TITLE
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 1, n_neighbors = 3

### ISSUE THREAD

**Issue by BeyondLee518** [ahaselsteiner/2020-paper-omae-hierarchical-models#2]
Hi Andreas,I'm running this model and the model made a mistake.How to solve it?
F:\wind-wave EC models\2020-paper-omae-hierarchical-models-master>python compute_contours_datasets_def.py
D:\python37\lib\site-packages\viroconcom\distributions.py:573: RuntimeWarning: invalid value encountered in log
  pstar_i = np.log10(-1.0 * np.log(1.0 - power_term))
D:\python37\lib\site-packages\viroconcom\distributions.py:590: RuntimeWarning: invalid value encountered in log
  xiHat = np.multiply(alphaHat, np.power(np.multiply(-1, np.log(1 - np.power(pi, 1.0 / delta))), 1.0 / betaHat))
D:\python37\lib\site-packages\viroconcom\distributions.py:573: RuntimeWarning: divide by zero encountered in log10
  pstar_i = np.log10(-1.0 * np.log(1.0 - power_term))
D:\python37\lib\site-packages\viroconcom\distributions.py:582: RuntimeWarning: invalid value encountered in double_scalars
  temp2 = sum(np.multiply(wi, np.power(pstar_i, 2))) - np.power(pstarbar, 2)
Optimization terminated successfully.
         Current function value: 0.003968
         Iterations: 17
         Function evaluations: 34
Traceback (most recent call last):
  File "compute_contours_datasets_def.py", line 59, in <module>
    do_search_for_optimal_start=True)
  File "F:\wind-wave EC models\2020-paper-omae-hierarchical-models-master\contour_statistics.py", line 88, in sort_points_to_form_continous_line
    G = clf.kneighbors_graph()
  File "D:\python37\lib\site-packages\sklearn\neighbors\_base.py", line 757, in kneighbors_graph
    A_ind = self.kneighbors(X, n_neighbors, return_distance=False)
  File "D:\python37\lib\site-packages\sklearn\neighbors\_base.py", line 617, in kneighbors
    (n_samples_fit, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 1, n_neighbors = 3

**Comment by ahaselsteiner** [comment]
Hi BeyondLee,

I guess you are using the code with your own dataset? Does your dataset contain 0-values?

In earlier versions of viroconcom we had a bug that the fitting procedure could not deal with 0-values, however, we have solved that in newer versions. If this were your problem, you could update viroconcom (pip uninstall viroconcom; pip install viroconcom) to solve the issue. 

In the newest version of viroconcom, however, we also changed the data structure of the .coordinates attribute such that you would then need to change the code by dropping the first index of the array, like this:

![image](https://user-images.githubusercontent.com/11452055/89291219-706fd780-d65a-11ea-990e-336a05f08cf1.png)


Let me know if that solved your issue.

Best, Andreas

**Comment by ahaselsteiner** [comment]
I just had a second look. The error is thrown by sort_points_to_form_continous_line, which uses G = clf.kneighbors_graph(). So there is likely another cause for the problem. It seems that the contours are getting computed, but then sorting the points does not work. 

Maybe the error is due to you using the newest version of viroconcom while this code was written for an earlier version of viroconcom (see requirements.txt, which says viroconcom==1.3.9)? We changed the datastructure of .coordinates. 

If you want to run the code with the newest version of viroconcom, it should urn if could you drop the first index of the array (as shown in my screenshot above). Alternatively, you could deinstall your current viroconcom and install viroconcom 1.3.9 (pip install -r requirements.txt)

Let me know if that solved your issue.

Best, Andreas

**Comment by BeyondLee518** [comment]
Yes, I have updated viroconcom, but after I run '2020-paper-omae-hierarchical-models-master>, python compute_contours_datasets_def. Py', that error still occurs, what should I do?Did you present this situation when you ran 2020-paper-omae-hierarchical-models-master>python compute_contours_datasets_def.py?

**Comment by BeyondLee518** [comment]
Thank you！ I can run before, now suddenly not, thank you very much

**Comment by ahaselsteiner** [comment]
So you got the code running now or the problem is still there?

**Comment by BeyondLee518** [comment]
I've solved it perfectly. You're a genius. You're awesome！
Thank you very much！！！

**Comment by BeyondLee518** [comment]
By the way, how to use MATLAB to find the three-parameter Weibull distribution, given the wave height data

**Comment by ahaselsteiner** [comment]
Glad to hear that adjusting the code for the newest version of viroconcom (?) solved the issue.

About using Matlab to estimate the parameters of a three-parameter Weibull distirbution: There are multiple 3-parameter Weibull distributions.

* If you want to estimate the parameters of an exponentiated Weibull distribution you might find this implementation handy: https://github.com/ahaselsteiner/exponentiated-weibull
* For a translated Weibull distribution, you might find this implementation handy: https://github.com/ahaselsteiner/translated-weibull

Best, Andreas

**Comment by yugao0912** [comment]
Hello Andreas,

I found a problem when I just want to validate the tool whether available. I did not change any codes but just run the code. There was a problem:


  File "....\2020-paper-omae-hierarchical-models-master\contour_statistics.py", line 87, in sort_points_to_form_continous_line
    clf = NearestNeighbors(2).fit(points)

TypeError: __init__() takes 1 positional argument but 2 were given.

What should I do, thank you so much.

Best,
Yu

**Comment by ahaselsteiner** [comment]
Hi Yu,

Thanks for writing about the problem. I am not sure yet what causes it but I'll try to figure it out with you.

Which command did you run that resulted in the error?

Often problems arise due to conflicting versions of Python packages. Did you type 

```
pip install -r requirements.txt
```

before running the scripts?

-Andreas

**Comment by yugao0912** [comment]
> Hi Yu,
> 
> Thanks for writing about the problem. I am not sure yet what causes it but I'll try to figure it out with you.
> 
> Which command did you run that resulted in the error?
> 
> Often problems arise due to conflicting versions of Python packages. Did you type
> 
> ```
> pip install -r requirements.txt
> ```
> 
> before running the scripts?
> 
> -Andreas

Hello Andreas,

Thank you for your response. I am not sure about that because my laptop is not by my side at this moment.

I will check it following your suggestion.

There is another problem which is about virocon. When I was trying to run the 3D_Contour using my data it always shows that ‘too few intervals at least 3 but get 2 only’. Additionally same problem with wind-wave contour.

I guess it’s because of my data format and the exponential weibull distribution doesn’t support my data after a series of comparison. But I am just starting using python I can not figure it out. I will be much appreciated that if you can help me with it.

Best regards,
Yu

**Comment by ahaselsteiner** [comment]
@yugao0912 for virocon feel free to open an issue in the virocon repository and describe the problem there: https://github.com/virocon-organization/virocon

We want to maintain the virocon code basis properly and are very interested in any problems users face :-)

**Comment by yugao0912** [comment]
Thank you Andreas,

I found I could not run 

pip install -r requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirement.txt'.

I can confirm that I have installed all the documents required.

Yu

**Comment by ahaselsteiner** [comment]
Did you have a typo?

The error message says no such file or directory 'requirement.txt' but the file name is 'requirements.txt' (there is an "s" in the end).

**Comment by yugao0912** [comment]
Yes, I have the typo.

and I can confirm that I type the file name correctly.

Thank you.

Yu
